---
title: "Austin Micromobility EDA"
output: html_notebook
---

```{r setup, include=FALSE}
source("code/packages.R")

knitr::opts_chunk$set(
  echo = FALSE,
  #fig.width = 6,
  fig.width = 9,
  fig.asp = 0.618,
  out.width = "70%",
  fig.align = "center",
  fig.show = "hold",
  eval = TRUE
)
```

# Exploration of the raw data

```{r}
loadd(raw_data)
glimpse(raw_data)
```

```{r}
raw_data %>%
  summarize_all(~ sum(is.na(.)))
```

```{r}
raw_data %>%
  count(vehicle_type)
```

```{r}
raw_data %>%
  group_by(vehicle_type, year) %>%
  summarize(
    n = n(),
    max_trip_duration = max(trip_duration_hours),
    min_trip_duration = min(trip_duration_hours),
    max_trip_distance = max(trip_distance_km),
    min_trip_distance = min(trip_distance_km)
    # min_average_speed = min(average_speed, na.rm = TRUE),
    # max_average_speed = max(average_speed, na.rm = TRUE)
  )
```

```{r}
raw_data %>%
  count(year(start_time))
```

```{r}
raw_data %>%
  count(year(end_time))
```

```{r}
raw_data %>%
  count(start_district)
```

```{r}
raw_data %>%
  count(end_district)
```

```{r}
raw_data %>%
  count(year)
```

# Exploration of the data after cleaning

```{r}
loadd(data)
glimpse(data)
```

```{r}
readd(n_obs_deleted)
```

```{r}
readd(trip_distance_plot)
```

```{r}
readd(trip_short_distance_plot)
```

```{r}
readd(trip_duration_plot)
```

```{r}
readd(trip_short_duration_plot)
```

```{r}
readd(council_district_scooter_2019_plot)
```

```{r}
readd(council_district_scooter_2020_plot)
```

```{r}
readd(council_district_bicycle_2019_plot)
```

```{r}
readd(council_district_bicycle_2020_plot)
```

```{r}
readd(all_freq_plot)
```

```{r}
readd(scooter_freq_plot)
```

```{r}
readd(bicycle_freq_plot)
```

```{r}
readd(all_freq_2019_plot)
```

```{r}
readd(scooter_freq_2019_plot)
```

```{r}
readd(bicycle_freq_2019_plot)
```
